### PR TITLE
 fix OnsUtils createDefaultStreams lost message body

### LINKED ISSUE #248: OnsUtilsHelper.createDefaultStreams lost ons message body
**Describe the bug**
ONS java/python api OnsUtilsHelper.createDefaultStreams  lost message body, only provide message length with Message.toString

### PR DESCRIPTION
**Pull request by wenxuanguan**
## What changes were proposed in this pull request?

fix #248 

## How was this patch tested?

(Please explain how this patch was tested. E.g. unit tests, integration tests, manual tests)

### CODE REVIEW

File: emr-ons/src/main/scala/org/apache/spark/streaming/aliyun/ons/OnsUtils.scala [hunk 1]
```diff
@@ -186,7 +188,9 @@ object OnsUtils {
       (msg: Message) => func.call(msg))
   }
 
-  private def extractMessage(msg: Message): Array[Byte] = msg.toString.getBytes
+  private def extractMessage(msg: Message): Array[Byte] = {
+    JSON.toJSONString(msg, new SerializeFilter{}).getBytes()
+  }
```
Comment (uncleGen) [inline emr-ons/src/main/scala/org/apache/spark/streaming/aliyun/ons/OnsUtils.scala]: provide a func: Array[Byte] => Message
